# Generated by Django 3.1.4 on 2021-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50)),
                ('account', models.CharField(max_length=10)),
                ('transact_amt', models.IntegerField(max_length=10, null=True)),
                ('balance', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
