# Generated by Django 3.1.4 on 2021-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20210321_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transact_amt',
            field=models.IntegerField(null=True),
        ),
    ]
